---
- name: cloudformation create beanstalk application and environment 
  cloudformation: >
    stack_name="beanstalkAppEnv"
    state=present
    region="{{aws_region}}"
    disable_rollback=true
    template="roles/cloudformation/templates/cf_app_env.json"
  args:
    template_parameters:
      KeyName: "{{key_name}}"
      SolutionStackName: "{{eb_solution_stack_name}}"
      EnvironmentName: "{{eb_environment_name}}"
      ApplicationName: "{{eb_application_name}}"
      ASGMin: "{{eb_asg_min}}"
      ASGMax: "{{eb_asg_max}}"
  register: stack

- name: show stack outputs  
  debug: msg="{{stack.stack_outputs}}"

#- name: set facts
#  set_fact:
#    bastion_ip: "{{stack.stack_outputs['BastionHostEIP']}}"
