---
- name: cloudformation create stack
  cloudformation: >
    stack_name="railsBeanstalk"
    state=present
    region="{{aws_region}}"
    disable_rollback=true
    template="roles/cloudformation/templates/arch.json"
  args:
    template_parameters:
      KeyName: "{{key_name}}"
      AvailabilityZoneA: "{{availability_zone_a}}"
      AvailabilityZoneB: "{{availability_zone_b}}"
  register: stack

- name: show stack outputs  
  debug: msg="{{stack.stack_outputs}}"

- name: set facts
  set_fact:
    bastion_ip: "{{stack.stack_outputs['BastionHostEIP']}}"
    private_subnet1: "{{stack.stack_outputs['PrivateSubnet1b']}}"
    private_subnet2: "{{stack.stack_outputs['PrivateSubnet1c']}}"
    public_subnet1: "{{stack.stack_outputs['PublicSubnet1b']}}"
    public_subnet2: "{{stack.stack_outputs['PublicSubnet1c']}}"
    security_group_id: "{{stack.stack_outputs['SecurityGroupId']}}"
    vpc_id: "{{stack.stack_outputs['VPC']}}"

- include: "roles/cloudformation/tasks/cf_rds.yml"
- include: "roles/cloudformation/tasks/cf_cache.yml"
#- include: "roles/cloudformation/tasks/beanstalk.yml"
